***Variables***

${_input_cliente}                          //input[@id="WC_UserRegistrationUpdateForm_FormInput_numCliente_In_Register_1"]
${_selec_list_dia}                         //select[@id="WC_UserRegistrationUpdateForm_FormSelect_diaNacimientoCliente_In_Register_1"]
${_selec_list_mes}                         //select[@id="WC_UserRegistrationUpdateForm_FormSelect_mesNacimientoCliente_In_Register_1"]
${_selec_list_anio}                         //select[@id="WC_UserRegistrationUpdateForm_FormSelect_anoNacimientoCliente_In_Register_1"]
${TIMEOUT}                           100s
