*** Variables ***

${_btn_menu_inicio_sesion}            //span[@data-nd2='Inicia sesión']
${_btn_crear_cuenta}                  //a[@data-nd3='Crear cuenta' and  @id='signOutQuickLink']
${_btn_inicar_sesion}                 //a[ @id='signInQuickLink']
${_opcion_crear_cuenta}               Crear cuenta
${_label_crear_cuenta}                //div[@id='WC_UserRegistrationAddForm_div_2']
${_opcion_iniciar_sesion}             Iniciar sesión
${_label_login}                       //span[ @class='login-title']

${_opcion_iniciar_sesion}             Iniciar sesion
${_btn_opcion_iniciar_sesion}         //a[@data-nd3='Iniciar sesión' and  @id='signInQuickLink']
${_label_iniciar_sesion}              //span[contains(text(),'Inicia sesión con tu correo')]
${_input_Correo_celular}              //input[@name='logonId']
${_input_contrasena}                  //input[@name='logonPassword']
${_button_iniciarSesion}              //a[@id="WC_AccountDisplay_links_2"]
