*** Variables ***

${_btn_menu_inicio_sesion}            //span[@data-nd2='Inicia sesión']
${_btn_crear_cuenta}                  //a[@data-nd3='Crear cuenta' and  @id='signOutQuickLink']
${_btn_inicar_sesion}                 //a[ @id='signInQuickLink']
${_opcion_crear_cuenta}               Crear cuenta
${_label_crear_cuenta}                //div[@id='WC_UserRegistrationAddForm_div_2']
${_opcion_iniciar_sesion}             Iniciar sesión
${_label_login}                       //span[ @class='login-title']
