*** Variables ***
${_txt_nombre_crear_cuenta}                //input[@id='WC_UserRegistrationAddForm_NameEntryForm_FormInput_firstName_1']
${_txt_apellido_crear_cuenta}              //input[@id='WC_UserRegistrationAddForm_NameEntryForm_FormInput_lastName_1']
${_txt_celular_correo_crear_cuenta}        //input[@id='WC_UserRegistrationAddForm_FormInput_email1_In_Register_1']
${_txt_contrasena_crear_cuenta}            //input[@id='WC_UserRegistrationAddForm_FormInput_logonPassword_In_Register_1']
${_rb_genero_crear_cuenta}                 gender
${_dato_female}                            Female
${_dato_male}                              Male
${_check_terminos_crear_cuenta}            //input[@id='WC_UserRegistrationAddForm_FormInput_termAndConditions_In_Register_1']
${_check_recibe_ofertas_crear_cuenta}      //input[@id='WC_UserRegistrationAddForm_EmailOption_Checkbox_1']
${_btn_crear_cuenta}                       //div[@id='WC_UserRegistrationAddForm_Buttons_1']
