*** Variables ***

${_txt_nombre}                //input[@id='WC_UserRegistrationAddForm_NameEntryForm_FormInput_firstName_1']
${_txt_apellido}              //input[@id='WC_UserRegistrationAddForm_NameEntryForm_FormInput_lastName_1']
${_txt_celular_correo}        //input[@id='WC_UserRegistrationAddForm_FormInput_email1_In_Register_1']
${_txt_contrasena}            //input[@id='WC_UserRegistrationAddForm_FormInput_logonPassword_In_Register_1']
${_rb_genero}                 gender
${_dato_female}               Female
${_dato_male}                 Male
${_check_terminos}            //input[@id='WC_UserRegistrationAddForm_FormInput_termAndConditions_In_Register_1']
${_check_recibe_ofertas}      //input[@id='WC_UserRegistrationAddForm_FormInput_sendMeEmail_In_Register_1']
${_btn_crear_cuenta}          //button[@id='WC_UserRegistrationAddForm_links_1']
