*** Variables ***

${_pupup_close}                       //span[@class="close-icon"]
${_icon_home}                         //div[@class="navbar-brand logo taggedRef"]
${_input_Correo_newsletter}           //input[@id="sendNewlatter"]
${_btn_registro_newletter}            //div[@class="buttonPlaceholder"]
${_popup_registro_satisfactorio}      //div[contains(text(),'se ha registrado satisfactoriamente')]
${_btn_registro_aceptar}              //button[contains(text(),'Aceptar')]
